package view;

import Controller.Proses;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import Model.Owner;
import Model.Barang;
import Model.Jenis_Barang;
import Model.Transaksi;
import Database.Koneksi;
import java.sql.ResultSet;


public final class TransaksiView extends javax.swing.JFrame {
    private Proses transaksi;
    private ArrayList<Transaksi> arrKeranjang;
    private Double hargatotal;
    private Koneksi koneksi;
   
    public TransaksiView() throws SQLException {
        initComponents();
        this.hargatotal = 0.0;
        this.transaksi = new Proses();        
        this.arrKeranjang = new ArrayList<>();
        this.showtblkeranjang();
        this.showtblpesanan();
        this.showComboBoxOwner();
        this.showComboBoxNamaBarang();
        this.showComboBoxHargaBarang();                        
        this.showHargaTotal();
        //this.viewTabel();
        
    }
    
    
    
    public void showtblkeranjang() {
        DefaultTableModel dtmKeranjang = new DefaultTableModel(new String[]{"ID Owner","ID Barang",
            "Nama Barang","Harga Barang",}, 0);
        for (Transaksi trans : this.arrKeranjang) {
                dtmKeranjang.addRow(new String[]{trans.getOwner().getId_owner().toString(),
                    trans.getBarang().getID_barang().toString(), trans.getBarang().getNama_barang(), 
                    trans.getBarang().getHarga_barang().toString()});
        }
        this.tblkeranjang.setModel(dtmKeranjang);
    }
    
    public void showtblpesanan() throws SQLException {
        DefaultTableModel dtmpesanan = new DefaultTableModel(new String[]{"Nama Owner", "Nama Barang",
            "Tanggal Transaksi", "Harga Total"}, 0);
        for (Transaksi p : this.arrKeranjang) {
            dtmpesanan.addRow(new String[]{p.getOwner().getNama_owner(),
                p.getNama_barang().getNama_barang(), p.getTgl_transaksi().toString(), p.getTotal_harga().toString()
            });
        }
        this.tblpesanan.setModel(dtmpesanan);
    }
    
    public void showComboBoxOwner() throws SQLException {
        DefaultComboBoxModel dcbmOwner = new DefaultComboBoxModel();
        for (Owner ow : this.transaksi.getDataOwner()) {
            dcbmOwner.addElement(ow.getNama_owner());
        }
        this.cbOwner.setModel(dcbmOwner);
    }
    
    public void showComboBoxNamaBarang() throws SQLException {
        DefaultComboBoxModel dcbmBarang = new DefaultComboBoxModel();
        for (Barang br : this.transaksi.getDataBarang()) {
            dcbmBarang.addElement(br.getNama_barang());
        }
        this.cbNamaBarang.setModel(dcbmBarang);
    } 

    public void showComboBoxHargaBarang() throws SQLException {
        DefaultComboBoxModel dcbmHargaBarang = new DefaultComboBoxModel();
        for (Barang br : this.transaksi.getDataBarang()) {
            dcbmHargaBarang.addElement(br.getHarga_barang());
        }
        this.cbHargaBarang.setModel(dcbmHargaBarang);
    }

    public void showHargaTotal() {
        tfTotalHarga.setText(hargatotal.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namapembeli = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        namausaha = new javax.swing.JLabel();
        jumlahbarang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namaowner = new javax.swing.JLabel();
        hargabarang = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tfNamaPembeli = new javax.swing.JTextField();
        tfJumlahBarang = new javax.swing.JTextField();
        totalharga = new javax.swing.JLabel();
        tfTotalHarga = new javax.swing.JTextField();
        ButtonTotal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkeranjang = new javax.swing.JTable();
        buttonsimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpesanan = new javax.swing.JTable();
        tgltransaksi = new javax.swing.JLabel();
        tfTglTransaksi = new javax.swing.JTextField();
        cbOwner = new javax.swing.JComboBox<>();
        cbNamaBarang = new javax.swing.JComboBox<>();
        cbHargaBarang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1500, 500));

        namapembeli.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        namapembeli.setText("Nama Pembeli");

        namabarang.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        namabarang.setText("Nama Barang");

        namausaha.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        namausaha.setText("KRIPIK PISANG MADU");

        jumlahbarang.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jumlahbarang.setText("Jumlah Barang");

        jLabel1.setText("____________________________________________________");

        namaowner.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        namaowner.setText("Nama Owner");

        hargabarang.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        hargabarang.setText("Harga Barang");

        alamat.setFont(new java.awt.Font("Arabic Typesetting", 1, 18)); // NOI18N
        alamat.setText("Jl. Bratang Binangun No.5, Surabaya Tengah, Jawa Timur");

        totalharga.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        totalharga.setText("Total Harga");

        ButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonTotal.setText("TOTAL");
        ButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTotalActionPerformed(evt);
            }
        });

        tblkeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblkeranjang);

        buttonsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonsimpan.setText("SIMPAN");
        buttonsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsimpanActionPerformed(evt);
            }
        });

        tblpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblpesanan);

        tgltransaksi.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        tgltransaksi.setText("Tgl Transaksi");

        cbOwner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNamaBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbHargaBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(totalharga)
                        .addGap(18, 18, 18)
                        .addComponent(tfTotalHarga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonTotal)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahbarang)
                            .addComponent(namabarang)
                            .addComponent(namapembeli)
                            .addComponent(namaowner)
                            .addComponent(hargabarang)
                            .addComponent(tgltransaksi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTglTransaksi)
                            .addComponent(tfJumlahBarang)
                            .addComponent(tfNamaPembeli)
                            .addComponent(cbNamaBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbHargaBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(namausaha))
                    .addComponent(alamat))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(namausaha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonsimpan)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namaowner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tgltransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(ButtonTotal)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTotalActionPerformed
        try {
            Transaksi tr = new Transaksi();
            tr.setJumlah_barang(Integer.parseInt(tfJumlahBarang.getText()));
            tr.setbarang(transaksi.getDataBarang().get(cbHargaBarang.getSelectedIndex()));
            this.hargatotal = this.transaksi.getDataBarang().get(cbHargaBarang.getSelectedIndex())
                    .getHarga_barang() * Integer.parseInt(tfJumlahBarang.getText());
            showHargaTotal();
            arrKeranjang.add(tr);
            tfJumlahBarang.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
         
    }//GEN-LAST:event_ButtonTotalActionPerformed

    private void buttonsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsimpanActionPerformed
            Transaksi p = new Transaksi();
        try {
            p.setOwner(this.transaksi.getDataOwner().get(this.cbOwner.getSelectedIndex()));
            p.setbarang(this.transaksi.getDataBarang().get(this.cbNamaBarang.getSelectedIndex()));
            p.setTgl_transaksi(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglTransaksi.getText()));
            
            p.setTotal_harga(this.hargatotal);
            p.setArrTransaksi(this.arrKeranjang);
            this.transaksi.insertTransaksi(p);
            this.showtblpesanan();
            this.arrKeranjang = new ArrayList<>();
            this.showtblkeranjang();
            this.hargatotal = 0.0;
            this.showHargaTotal();
            this.showComboBoxNamaBarang();
        } catch (SQLException | ParseException err) {
            System.out.println(err);
        } 
    }//GEN-LAST:event_buttonsimpanActionPerformed
                                 
                                     
        
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTotal;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton buttonsimpan;
    private javax.swing.JComboBox<String> cbHargaBarang;
    private javax.swing.JComboBox<String> cbNamaBarang;
    private javax.swing.JComboBox<String> cbOwner;
    private javax.swing.JLabel hargabarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlahbarang;
    private javax.swing.JLabel namabarang;
    private javax.swing.JLabel namaowner;
    private javax.swing.JLabel namapembeli;
    private javax.swing.JLabel namausaha;
    private javax.swing.JTable tblkeranjang;
    private javax.swing.JTable tblpesanan;
    private javax.swing.JTextField tfJumlahBarang;
    private javax.swing.JTextField tfNamaPembeli;
    private javax.swing.JTextField tfTglTransaksi;
    private javax.swing.JTextField tfTotalHarga;
    private javax.swing.JLabel tgltransaksi;
    private javax.swing.JLabel totalharga;
    // End of variables declaration//GEN-END:variables
}
